system:
  pulsar:
    container: !system/component
      system/component-kind: pulsar/container
      exposed-ports: [6650, 8080]

    container-service-port: !system/component
      system/component-kind: pulsar/container-service-port
      container: !system/local-ref container
      exposed-port: 6650

    container-service-url: !system/component
      system/component-kind: pulsar/container-service-url
      port: !system/local-ref container-service-port
      scheme: pulsar

    container-service-http-port: !system/component
      system/component-kind: pulsar/container-service-http-port
      container: !system/local-ref container
      exposed-port: 8080

    container-service-http-url: !system/component
      system/component-kind: pulsar/container-service-http-url
      port: !system/local-ref container-service-http-port
      scheme: http

    client: !system/component
      system/component-kind: pulsar/client
      service-url: !system/local-ref container-service-url

    admin: !system/component
      system/component-kind: pulsar/admin
      service-http-url: !system/local-ref container-service-http-url

    schemas: !system/component
      system/component-kind: pulsar/schemas
      command:
        schema: schemas/command/command-envelope.avsc.json
        type: AVRO
      command-response:
        schema: schemas/command/command-response.avsc.json
        type: AVRO

    tenants: !system/component
      system/component-kind: pulsar/tenants
      admin: !system/local-ref admin
      tenants:
        - tenant: tenant-1
          clusters: [standalone]
          roles: []

    namespaces: !system/component
      system/component-kind: pulsar/namespaces
      _: !system/local-ref tenants
      admin: !system/local-ref admin
      namespaces:
        - namespace: "tenant-1/namespace-1"
          config:
            post:
              autoTopicCreation:
                allowAutoTopicCreation: false
                defaultNumPartitions: 1
                topicType: string
              isAllowAutoUpdateSchema: false
              schemaValidationEnforced: true
            put:
              schemaCompatibilityStrategy: FULL

    topics: !system/component
      system/component-kind: pulsar/topics
      _: !system/local-ref namespaces
      admin: !system/local-ref admin
      schemas: !system/local-ref schemas
      topics:
        - topic: "persistent://tenant-1/namespace-1/topic-cash-cash-accounts-command"
          partitions: 1
          schema: !keyword command
        - topic: "persistent://tenant-1/namespace-1/topic-cash-cash-accounts-command-response"
          partitions: 1
          schema: !keyword command-response
        - topic: "persistent://tenant-1/namespace-1/topic-parties-command"
          partitions: 1
          schema: !keyword command
        - topic: "persistent://tenant-1/namespace-1/topic-parties-command-response"
          partitions: 1
          schema: !keyword command-response
        - topic: "persistent://tenant-1/namespace-1/topic-transactions-command"
          partitions: 1
          schema: !keyword command
        - topic: "persistent://tenant-1/namespace-1/topic-transactions-command-response"
          partitions: 1
          schema: !keyword command-response

    producers: !system/component
      system/component-kind: pulsar/producers
      cash-accounts-command:
        _: !system/local-ref topics
        client: !system/local-ref client
        conf:
          accessMode: !pulsar/access-mode Shared
          schema: !keyword command
          topicName: "persistent://tenant-1/namespace-1/topic-cash-cash-accounts-command"
        schemas: !system/local-ref schemas
      cash-accounts-command-response:
        _: !system/local-ref topics
        client: !system/local-ref client
        conf:
          accessMode: !pulsar/access-mode Shared
          schema: !keyword command-response
          topicName: "persistent://tenant-1/namespace-1/topic-cash-cash-accounts-command-response"
        schemas: !system/local-ref schemas
      parties-command:
        _: !system/local-ref topics
        client: !system/local-ref client
        conf:
          accessMode: !pulsar/access-mode Shared
          schema: !keyword command
          topicName: "persistent://tenant-1/namespace-1/topic-parties-command"
        schemas: !system/local-ref schemas
      parties-command-response:
        _: !system/local-ref topics
        client: !system/local-ref client
        conf:
          accessMode: !pulsar/access-mode Shared
          schema: !keyword command-response
          topicName: "persistent://tenant-1/namespace-1/topic-parties-command-response"
        schemas: !system/local-ref schemas
      transactions-command:
        _: !system/local-ref topics
        client: !system/local-ref client
        conf:
          accessMode: !pulsar/access-mode Shared
          schema: !keyword command
          topicName: "persistent://tenant-1/namespace-1/topic-transactions-command"
        schemas: !system/local-ref schemas
      transactions-command-response:
        _: !system/local-ref topics
        client: !system/local-ref client
        conf:
          accessMode: !pulsar/access-mode Shared
          schema: !keyword command-response
          topicName: "persistent://tenant-1/namespace-1/topic-transactions-command-response"
        schemas: !system/local-ref schemas

    consumers: !system/component
      system/component-kind: pulsar/consumers
      cash-accounts-command:
        _: !system/local-ref topics
        client: !system/local-ref client
        conf:
          cryptoFailureAction: !pulsar/crypto-failure-action CONSUME
          schema: !pulsar/schema AUTO_CONSUME
          subscriptionName: bank-monolith-cash-accounts-command
          subscriptionType: !pulsar/subscription-type Shared
          topicNames:
            ["persistent://tenant-1/namespace-1/topic-cash-cash-accounts-command"]
        schemas: !system/local-ref schemas
      cash-accounts-command-response:
        _: !system/local-ref topics
        client: !system/local-ref client
        conf:
          cryptoFailureAction: !pulsar/crypto-failure-action CONSUME
          schema: !pulsar/schema AUTO_CONSUME
          subscriptionName: bank-monolith-cash-accounts-command-response
          subscriptionType: !pulsar/subscription-type Shared
          topicNames:
            ["persistent://tenant-1/namespace-1/topic-cash-cash-accounts-command-response"]
        schemas: !system/local-ref schemas
      parties-command:
        _: !system/local-ref topics
        client: !system/local-ref client
        conf:
          cryptoFailureAction: !pulsar/crypto-failure-action CONSUME
          schema: !pulsar/schema AUTO_CONSUME
          subscriptionName: bank-monolith-parties-command
          subscriptionType: !pulsar/subscription-type Shared
          topicNames:
            ["persistent://tenant-1/namespace-1/topic-parties-command"]
        schemas: !system/local-ref schemas
      parties-command-response:
        _: !system/local-ref topics
        client: !system/local-ref client
        conf:
          cryptoFailureAction: !pulsar/crypto-failure-action CONSUME
          schema: !pulsar/schema AUTO_CONSUME
          subscriptionName: bank-monolith-parties-command-response
          subscriptionType: !pulsar/subscription-type Shared
          topicNames:
            ["persistent://tenant-1/namespace-1/topic-parties-command-response"]
        schemas: !system/local-ref schemas
      transactions-command:
        _: !system/local-ref topics
        client: !system/local-ref client
        conf:
          cryptoFailureAction: !pulsar/crypto-failure-action CONSUME
          schema: !pulsar/schema AUTO_CONSUME
          subscriptionName: bank-monolith-transactions-command
          subscriptionType: !pulsar/subscription-type Shared
          topicNames:
            ["persistent://tenant-1/namespace-1/topic-transactions-command"]
        schemas: !system/local-ref schemas
      transactions-command-response:
        _: !system/local-ref topics
        client: !system/local-ref client
        conf:
          cryptoFailureAction: !pulsar/crypto-failure-action CONSUME
          schema: !pulsar/schema AUTO_CONSUME
          subscriptionName: bank-monolith-transactions-command-response
          subscriptionType: !pulsar/subscription-type Shared
          topicNames:
            ["persistent://tenant-1/namespace-1/topic-transactions-command-response"]
        schemas: !system/local-ref schemas

    message-bus-producers: !system/component
      system/component-kind: pulsar/message-bus-producers
      cash-accounts-command:
        producer: !system/local-ref producers.cash-accounts-command
      cash-accounts-command-response:
        producer: !system/local-ref producers.cash-accounts-command-response
      parties-command:
        producer: !system/local-ref producers.parties-command
      parties-command-response:
        producer: !system/local-ref producers.parties-command-response
      transactions-command:
        producer: !system/local-ref producers.transactions-command
      transactions-command-response:
        producer: !system/local-ref producers.transactions-command-response

    message-bus-consumers: !system/component
      system/component-kind: pulsar/message-bus-consumers
      cash-accounts-command:
        consumer: !system/local-ref consumers.cash-accounts-command
      cash-accounts-command-response:
        consumer: !system/local-ref consumers.cash-accounts-command-response
      parties-command:
        consumer: !system/local-ref consumers.parties-command
      parties-command-response:
        consumer: !system/local-ref consumers.parties-command-response
      transactions-command:
        consumer: !system/local-ref consumers.transactions-command
      transactions-command-response:
        consumer: !system/local-ref consumers.transactions-command-response

  message-bus:
    bus: !system/component
      system/component-kind: message-bus/bus
      producers: !system/ref pulsar.message-bus-producers
      consumers: !system/ref pulsar.message-bus-consumers

  fdb: !include bank/fdb-test.yml
  avro: !include avro/avro-test.yml
  cash-accounts:
    processor: !system/component
      system/component-kind: cash-accounts/processor
      record-db: !system/ref fdb.record-db
      record-store: !system/ref fdb.store
      schemas: !system/ref avro.serde
    command-processor: !system/component
      system/component-kind: command-processor/command-processor
      bus: !system/ref message-bus.bus
      processor: !system/local-ref processor
      command-channel: !keyword cash-accounts-command
      command-response-channel: !keyword cash-accounts-command-response
    watcher-handler: !system/component
      system/component-kind: cash-accounts/watcher-handler
      record-store: !system/ref fdb.store
    watcher: !system/component
      system/component-kind: fdb/watcher
      record-db: !system/ref fdb.record-db
      consumer-id: cash-accounts-watcher
      store-name: cash-accounts
      handler: !system/local-ref watcher-handler
    dispatcher: !system/component
      system/component-kind: command/dispatcher
      bus: !system/ref message-bus.bus
      command-channel: !keyword cash-accounts-command
      command-response-channel: !keyword cash-accounts-command-response
  parties:
    processor: !system/component
      system/component-kind: party/processor
      record-db: !system/ref fdb.record-db
      record-store: !system/ref fdb.store
      schemas: !system/ref avro.serde
    command-processor: !system/component
      system/component-kind: command-processor/command-processor
      bus: !system/ref message-bus.bus
      processor: !system/local-ref processor
      command-channel: !keyword parties-command
      command-response-channel: !keyword parties-command-response
    watcher-handler: !system/component
      system/component-kind: party/watcher-handler
      record-store: !system/ref fdb.store
    watcher: !system/component
      system/component-kind: fdb/watcher
      record-db: !system/ref fdb.record-db
      consumer-id: parties-watcher
      store-name: idvs
      handler: !system/local-ref watcher-handler
    dispatcher: !system/component
      system/component-kind: command/dispatcher
      bus: !system/ref message-bus.bus
      command-channel: !keyword parties-command
      command-response-channel: !keyword parties-command-response
  transactions:
    processor: !system/component
      system/component-kind: transactions/processor
      record-db: !system/ref fdb.record-db
      record-store: !system/ref fdb.store
      schemas: !system/ref avro.serde
    command-processor: !system/component
      system/component-kind: command-processor/command-processor
      bus: !system/ref message-bus.bus
      processor: !system/local-ref processor
      command-channel: !keyword transactions-command
      command-response-channel: !keyword transactions-command-response
    dispatcher: !system/component
      system/component-kind: command/dispatcher
      bus: !system/ref message-bus.bus
      command-channel: !keyword transactions-command
      command-response-channel: !keyword transactions-command-response
  idv:
    processor: !system/component
      system/component-kind: idv/processor
      record-db: !system/ref fdb.record-db
      record-store: !system/ref fdb.store
      schemas: !system/ref avro.serde
    party-watcher-handler: !system/component
      system/component-kind: idv/party-watcher-handler
      record-store: !system/ref fdb.store
    party-watcher: !system/component
      system/component-kind: fdb/watcher
      record-db: !system/ref fdb.record-db
      consumer-id: idv-party-watcher
      store-name: parties
      handler: !system/local-ref party-watcher-handler
    watcher-handler: !system/component
      system/component-kind: idv/watcher-handler
      record-store: !system/ref fdb.store
    watcher: !system/component
      system/component-kind: fdb/watcher
      record-db: !system/ref fdb.record-db
      consumer-id: idv-watcher
      store-name: idvs
      handler: !system/local-ref watcher-handler
  bootstrap: !include bank/bootstrap-internal-test.yml
  telemetry:
    otel-sdk: !profile
      dev: !system/component
        system/component-kind: telemetry/otel-sdk
        service-name: bank-monolith
        endpoint: http://localhost:4318/v1/traces
  server:
    handler: !system/required-component
    interceptors: !system/component
      system/component-kind: server/interceptors
      admin-api-key: !env MONO_ADMIN_API_KEY
      bootstrap: !system/ref bootstrap.internal
      dispatchers:
        cash-accounts: !system/ref cash-accounts.dispatcher
        parties: !system/ref parties.dispatcher
        transactions: !system/ref transactions.dispatcher
      avro: !system/ref avro.serde
      record-db: !system/ref fdb.record-db
      record-store: !system/ref fdb.store
    jetty-adapter: !system/component
      system/component-kind: server/jetty-adapter
      handler: !system/ref server.handler
      interceptors: !system/ref server.interceptors
      options: !profile
        dev:
          port: 8080
