system:
  message-bus: !include bank-api/message-bus-test.yml
  avro: !include avro/avro-test.yml
  cash-accounts:
    dispatcher: !system/component
      system/component-kind: command/dispatcher
      bus: !system/ref message-bus.bus
      command-channel: !keyword cash-accounts-command
      command-response-channel: !keyword cash-accounts-command-response
  parties:
    dispatcher: !system/component
      system/component-kind: command/dispatcher
      bus: !system/ref message-bus.bus
      command-channel: !keyword parties-command
      command-response-channel: !keyword parties-command-response
  payments:
    dispatcher: !system/component
      system/component-kind: command/dispatcher
      bus: !system/ref message-bus.bus
      command-channel: !keyword payments-command
      command-response-channel: !keyword payments-command-response
  interest:
    dispatcher: !system/component
      system/component-kind: command/dispatcher
      bus: !system/ref message-bus.bus
      command-channel: !keyword interest-command
      command-response-channel: !keyword interest-command-response
  server: !include bank-api/server-test.yml
